import type {
  Contract,
  Invoice,
  PayoutAccount,
  RequestProject,
  UserProfile,
} from "./types";

const progress = (
  status: Invoice["status"],
): RequestProject["progress"] => {
  const signatureComplete = status !== "DRAFT_SIGNATURE";
  const reviewComplete = ["APPROVED", "PAYMENT_FAILED", "PAID"].includes(status);
  const paymentComplete = status === "PAID";
  return [
    { id: "contract", label: "合同匹配", state: "complete", description: "已匹配当前账号下的同名合同", owner: "系统", time: "已完成" },
    { id: "invoice", label: "Invoice 签署", state: signatureComplete ? "complete" : "current", description: signatureComplete ? "Invoice 已完成签署" : "等待你核对并签署 Invoice", owner: signatureComplete ? "系统" : "你", time: signatureComplete ? "已完成" : "待处理" },
    { id: "review", label: "Invoice 审核", state: reviewComplete ? "complete" : signatureComplete ? "current" : "pending", description: reviewComplete ? "Invoice 已通过审核" : signatureComplete ? "Invoice 正在审核" : "签署后进入审核", owner: "系统", time: reviewComplete ? "已完成" : signatureComplete ? "处理中" : "未开始" },
    { id: "payment", label: "完成付款", state: paymentComplete ? "complete" : status === "PAYMENT_FAILED" ? "blocked" : reviewComplete ? "current" : "pending", description: paymentComplete ? "款项已完成支付" : status === "PAYMENT_FAILED" ? "付款信息校验失败，需要修正后提交审核" : reviewComplete ? "等待付款处理" : "Invoice 审核通过后进入付款", owner: "系统", time: paymentComplete ? "已完成" : status === "PAYMENT_FAILED" ? "已暂停" : reviewComplete ? "处理中" : "未开始" },
  ];
};

const standardKolObligations: Contract["obligations"] = [
  {
    id: "delivery",
    category: "交付",
    title: "按约完成内容交付",
    summary: "先提交视频创意脚本，再制作并发布法语 YouTube 横版推广视频；描述区需包含品牌提供的 CTA、追踪链接及指定话题。",
    clause: "IO 第2条（Services / Deliverables）",
    timing: "按项目排期完成",
    stage: "履约中",
  },
  {
    id: "approval",
    category: "发布",
    title: "发布前确认并配合修改",
    summary: "未经 COMETS 书面确认不得发布；需在指定时间内完成合理修改，约定范围内最多配合三轮修改。",
    clause: "标准条款第9(iv)(v)条、IO 第6条",
    timing: "发布前完成",
    stage: "履约中",
  },
  {
    id: "retention",
    category: "发布",
    title: "内容留存与下架配合",
    summary: "内容发布后需在频道保留至少一年；若内容对品牌造成不利影响，应按要求及时修改、撤回或删除。",
    clause: "标准条款第2.3条、IO 第4条",
    timing: "发布后持续履行",
    stage: "履约中",
  },
  {
    id: "compliance",
    category: "合规",
    title: "保证内容合规及知识产权",
    summary: "不得包含禁限内容或侵犯第三方权利，并应确保有权授予品牌在约定范围内使用、展示和传播交付内容。",
    clause: "标准条款第2.5条、第5.1-5.3条",
    timing: "全服务周期",
    stage: "履约中",
  },
  {
    id: "confidentiality",
    category: "保密",
    title: "履行保密与及时响应义务",
    summary: "不得披露未公开素材、合同条款及报酬信息；连续七日不得失联，如无法按期交付需及时书面申请延期。",
    clause: "标准条款第7.1-7.2条、第9(ii)(iii)条",
    timing: "全服务周期",
    stage: "履约中",
  },
  {
    id: "invoice",
    category: "请款",
    title: "提交有效 Invoice 与准确收款资料",
    summary: "终验通过后需在三个工作日内提交有效 Invoice，并保证 Invoice 与收款账户信息准确、完整且一致。",
    clause: "标准条款第3.2-3.6条、IO 第5条",
    timing: "终验通过后 3 个工作日内",
    stage: "请款前",
  },
];

const standardContractFile = {
  fileName: "26-kol-standard-terms-template.pdf",
  documentUrl: "/26-kol-standard-terms-template.pdf",
  pageCount: 16,
  obligations: standardKolObligations,
};

export const contracts: Contract[] = [
  {
    ...standardContractFile,
    id: "CON-260724-KOL-01",
    orderId: "IO-260724-NQ-FR",
    projectId: "REQ-260727-NQ-FR",
    projectName: "Nebula Quest 法国推广",
    campaignName: "Nebula Quest 法国推广",
    brand: "Nebula Quest",
    creatorName: "Léa Martin",
    amount: "EUR 8,500",
    effectiveDate: "2026-07-15",
    servicePeriod: "2026-07-15 至 2026-09-30",
    status: "未请款",
    updatedAt: "2026-07-24",
  },
  {
    ...standardContractFile,
    id: "CON-260727-KOL-02",
    orderId: "IO-260727-NQ-ADD",
    projectId: "REQ-260727-NQ-ADD",
    projectName: "Nebula Quest 短视频加投",
    campaignName: "Nebula Quest 短视频加投",
    brand: "Nebula Quest",
    creatorName: "Léa Martin",
    amount: "EUR 1,200",
    effectiveDate: "2026-07-20",
    servicePeriod: "2026-07-20 至 2026-08-20",
    status: "未请款",
    updatedAt: "2026-07-27",
  },
  {
    ...standardContractFile,
    id: "CON-260716-KOL-03",
    orderId: "IO-260716-NL-UNBOX",
    projectId: "REQ-240716-NL-UNBOX",
    projectName: "新品开箱",
    campaignName: "新品开箱",
    brand: "Nova Lab",
    creatorName: "Léa Martin",
    amount: "EUR 2,450",
    effectiveDate: "2026-06-18",
    servicePeriod: "2026-06-18 至 2026-07-16",
    status: "未请款",
    updatedAt: "2026-07-16",
  },
  {
    ...standardContractFile,
    id: "CON-260711-KOL-04",
    orderId: "IO-260711-MH-COLLAB",
    projectId: "REQ-260728-MH-JULY",
    projectName: "七月联名",
    campaignName: "七月联名",
    brand: "Mellow Home",
    creatorName: "Léa Martin",
    amount: "USD 2,100",
    effectiveDate: "2026-06-10",
    servicePeriod: "2026-06-10 至 2026-07-10",
    status: "请款中",
    updatedAt: "2026-07-28",
  },
  {
    ...standardContractFile,
    id: "CON-260718-KOL-05",
    orderId: "IO-260718-SB-LIVE",
    projectId: "REQ-240718-SB-LIVE",
    projectName: "夏日直播计划",
    campaignName: "夏日直播计划",
    brand: "Solara Beauty",
    creatorName: "Léa Martin",
    amount: "USD 3,240",
    effectiveDate: "2026-06-15",
    servicePeriod: "2026-06-15 至 2026-07-15",
    status: "请款中",
    updatedAt: "2026-07-28",
  },
  {
    ...standardContractFile,
    id: "CON-260625-KOL-06",
    orderId: "IO-260625-AM-JP",
    projectId: "REQ-240625-AM-JP",
    projectName: "日本市场测评",
    campaignName: "日本市场测评",
    brand: "Aster Mobile",
    creatorName: "Léa Martin",
    amount: "USD 3,800",
    effectiveDate: "2026-05-20",
    servicePeriod: "2026-05-20 至 2026-06-20",
    status: "已付款",
    updatedAt: "2026-07-16",
  },
  {
    ...standardContractFile,
    id: "CON-260711-KOL-07",
    orderId: "IO-260711-MH-SUMMER",
    projectId: "REQ-240711-MH-SUMMER",
    projectName: "夏季家居专题",
    campaignName: "夏季家居专题",
    brand: "Mellow Home",
    creatorName: "Léa Martin",
    amount: "USD 2,100",
    effectiveDate: "2026-06-01",
    servicePeriod: "2026-06-01 至 2026-07-05",
    status: "请款中",
    updatedAt: "2026-07-28",
  },
  {
    ...standardContractFile,
    id: "CON-260714-KOL-08",
    orderId: "IO-260714-NL-REVIEW",
    projectId: "REQ-240714-NL-REVIEW",
    projectName: "新品体验测评",
    campaignName: "新品体验测评",
    brand: "Nova Lab",
    creatorName: "Léa Martin",
    amount: "EUR 1,850",
    effectiveDate: "2026-06-12",
    servicePeriod: "2026-06-12 至 2026-07-12",
    status: "请款中",
    updatedAt: "2026-07-19",
  },
];

export const invoices: Invoice[] = [
  { id: "INV-20260727-00001", projectId: "REQ-240711-MH-SUMMER", projectName: "夏季家居专题", brand: "Mellow Home", channel: "Airwallex", amount: "USD 2,100", status: "DRAFT_SIGNATURE", issuedAt: "2026-07-27", updatedAt: "今天 14:30", invoiceType: "EXTERNAL_CONTRACT", payoutAccountId: "payout-awx-fr-primary" },
  {
    id: "INV-20260728-00001",
    projectId: "REQ-260728-MH-JULY",
    projectName: "七月联名",
    brand: "Mellow Home",
    channel: "Airwallex",
    amount: "USD 2,100",
    status: "PAYMENT_FAILED",
    issuedAt: "2026-07-28",
    updatedAt: "今天 16:20",
    invoiceType: "EXTERNAL_CONTRACT",
    payoutAccountId: "payout-awx-fr-primary",
    paymentIssue: {
      version: 1,
      code: "INVALID_ACCOUNT_NUMBER",
      fieldKey: "account_number",
      fieldLabel: "银行账号 / Bank account number",
      maskedValue: "···· 0189",
      invalidValue: "FR7630006000011234567890189",
      message: "Airwallex 在发起付款时无法验证该银行账号与当前收款银行记录一致，本次付款已暂停。",
    },
  },
  { id: "INV-20260718-00001", projectId: "REQ-240718-SB-LIVE", projectName: "夏日直播计划", brand: "Solara Beauty", channel: "Airwallex", amount: "USD 3,240", status: "PENDING_REVIEW", issuedAt: "2026-07-18", updatedAt: "今天 10:12", invoiceType: "EXTERNAL_CONTRACT", payoutAccountId: "payout-awx-fr-primary" },
  { id: "INV-20260714-00001", projectId: "REQ-240714-NL-REVIEW", projectName: "新品体验测评", brand: "Nova Lab", channel: "Airwallex", amount: "EUR 1,850", status: "APPROVED", issuedAt: "2026-07-14", updatedAt: "07-19 09:30", invoiceType: "EXTERNAL_CONTRACT", payoutAccountId: "payout-awx-fr-primary" },
  { id: "INV-20260625-00001", projectId: "REQ-240625-AM-JP", projectName: "日本市场测评", brand: "Aster Mobile", channel: "Airwallex", amount: "USD 3,800", status: "PAID", issuedAt: "2026-06-25", updatedAt: "07-16 14:32", paymentReference: "AWX-PAY-881029", invoiceType: "EXTERNAL_CONTRACT", payoutAccountId: "payout-awx-fr-primary" },
];

export const requests: RequestProject[] = [
  { id: "REQ-260728-MH-JULY", projectName: "七月联名", brand: "Mellow Home", amount: "USD 2,100", status: "PAYMENT_FAILED", contractIds: ["CON-260711-KOL-04"], invoiceIds: ["INV-20260728-00001"], contractStatus: "请款中", invoiceStatus: "付款异常", updatedAt: "今天 16:20", progress: progress("PAYMENT_FAILED"), issues: [{ id: "ISSUE-01", type: "PAYOUT", title: "付款信息校验失败", reason: "发起付款时银行账号校验未通过，请在个人档案中修正并完成 Airwallex 校验后提交审核。", resourceId: "INV-20260728-00001", owner: "你", resolved: false }] },
  { id: "REQ-240711-MH-SUMMER", projectName: "夏季家居专题", brand: "Mellow Home", amount: "USD 2,100", status: "DRAFT_SIGNATURE", contractIds: ["CON-260711-KOL-07"], invoiceIds: ["INV-20260727-00001"], contractStatus: "请款中", invoiceStatus: "待确认", updatedAt: "今天 14:30", progress: progress("DRAFT_SIGNATURE"), issues: [] },
  { id: "REQ-240718-SB-LIVE", projectName: "夏日直播计划", brand: "Solara Beauty", amount: "USD 3,240", status: "PENDING_REVIEW", contractIds: ["CON-260718-KOL-05"], invoiceIds: ["INV-20260718-00001"], contractStatus: "请款中", invoiceStatus: "待审核", updatedAt: "今天 10:12", progress: progress("PENDING_REVIEW"), issues: [] },
  { id: "REQ-240714-NL-REVIEW", projectName: "新品体验测评", brand: "Nova Lab", amount: "EUR 1,850", status: "APPROVED", contractIds: ["CON-260714-KOL-08"], invoiceIds: ["INV-20260714-00001"], contractStatus: "请款中", invoiceStatus: "待付款", updatedAt: "07-19 09:30", progress: progress("APPROVED"), issues: [] },
  { id: "REQ-240625-AM-JP", projectName: "日本市场测评", brand: "Aster Mobile", amount: "USD 3,800", status: "PAID", contractIds: ["CON-260625-KOL-06"], invoiceIds: ["INV-20260625-00001"], contractStatus: "已付款", invoiceStatus: "已付款", updatedAt: "07-16 14:32", progress: progress("PAID"), issues: [] },
];

const primaryPayoutAccount: PayoutAccount = {
  id: "payout-awx-fr-primary",
  name: "France EUR 主账户",
  provider: "Airwallex",
  channel: "AIRWALLEX",
  accountHolder: "Lea Martin",
  bankCountry: "France",
  bankName: "BNP Paribas",
  currency: "EUR",
  beneficiaryType: "PERSONAL",
  transferMethod: "LOCAL",
  accountNumber: "FR7630006000011234567890189",
  swiftCode: "BNPAFRPP",
  status: "VALIDATED",
  beneficiaryId: "bene_mock_lea_001",
  linkages: {
    projectCount: 5,
    invoiceCount: 5,
    paymentBatchCount: 5,
    transactionCount: 1,
  },
  hasActivePayment: false,
  schemaValues: {
    account_name: "Lea Martin",
    account_number: "FR7630006000011234567890189",
    bank_name: "BNP Paribas",
    bank_street_address:
      "16 Boulevard des Italiens, 75009 Paris, France",
    swift_code: "BNPAFRPP",
    iban: "FR7630006000011234567890189",
  },
};

const secondaryPayoutAccount: PayoutAccount = {
  id: "payout-awx-jp-backup",
  name: "Japan JPY 备用账户",
  provider: "Airwallex",
  channel: "AIRWALLEX",
  accountHolder: "Lea Martin",
  bankCountry: "Japan",
  bankName: "MUFG Bank",
  currency: "JPY",
  beneficiaryType: "PERSONAL",
  transferMethod: "LOCAL",
  accountNumber: "0008921",
  swiftCode: "BOTKJPJT",
  status: "VALIDATED",
  beneficiaryId: "bene_mock_lea_002",
  linkages: {
    projectCount: 0,
    invoiceCount: 0,
    paymentBatchCount: 0,
    transactionCount: 0,
  },
  hasActivePayment: false,
  schemaValues: {
    account_name: "Lea Martin",
    account_number: "0008921",
    bank_name: "MUFG Bank",
    bank_street_address:
      "2-7-1 Marunouchi, Chiyoda-ku, Tokyo 100-8388, Japan",
    swift_code: "BOTKJPJT",
  },
};

const paypalPayoutAccount: PayoutAccount = {
  id: "payout-paypal-backup",
  name: "PayPal 备用账户",
  provider: "PayPal",
  channel: "PAYPAL",
  accountHolder: "Lea Martin",
  accountEmail: "lea.martin@creator.example",
  bankCountry: "France",
  bankName: "",
  currency: "EUR",
  beneficiaryType: "PERSONAL",
  transferMethod: "LOCAL",
  accountNumber: "",
  swiftCode: "",
  status: "PENDING_CONFIRMATION",
  linkages: {
    projectCount: 0,
    invoiceCount: 0,
    paymentBatchCount: 0,
    transactionCount: 0,
  },
  hasActivePayment: false,
  schemaValues: {
    paypal_email: "lea.martin@creator.example",
  },
};

export const initialProfile: UserProfile = {
  id: "CREATOR-001",
  displayName: "Léa Martin",
  legalName: "Léa Martin",
  email: "lea.martin@creator.example",
  phone: "+33 6 12 34 56 78",
  country: "法国",
  address: "24 Rue du Faubourg Saint-Honoré, 75008 Paris, France",
  social: {
    platform: "YouTube",
    handle: "@LeaPlayFR",
    profileUrl: "https://youtube.com/@LeaPlayFR",
    profileUrls: [
      "https://youtube.com/@LeaPlayFR",
      "https://instagram.com/leaplayfr",
    ],
    verificationStatus: "VERIFIED",
    screenshot: { id: "FILE-001", name: "youtube-studio-leaplayfr.png", mimeType: "image/png", size: 884000 },
    screenshots: [
      { id: "FILE-001", name: "youtube-studio-leaplayfr.png", mimeType: "image/png", size: 884000 },
    ],
  },
  payout: primaryPayoutAccount,
  payoutAccounts: [
    primaryPayoutAccount,
    secondaryPayoutAccount,
    paypalPayoutAccount,
  ],
  defaultPayoutAccountId: primaryPayoutAccount.id,
  payoutAccountsVersion: 2,
};
