import type { TFunction } from "i18next";
import i18n from "./i18n";

// Presentation-only mapping: status codes, stored records and form values stay unchanged.
const keys: Record<string, string> = {
  PENDING_CONFIRMATION: "status.awaitingConfirmation",
  DRAFT_SIGNATURE: "status.awaitingConfirmation",
  PENDING_REVIEW: "status.awaitingReview",
  CHANGES_REQUIRED: "status.changesRequired",
  APPROVED: "status.approved",
  PAYMENT_FAILED: "status.paymentIssue",
  PAID: "status.paid",
  PENDING_SIGNATURE: "status.awaitingSignature",
  ACTIVE: "status.active",
  EXPIRED: "status.expired",
  "当前管理员账号无权进入创作者工作台。": "admin.creatorAccessDenied",
  "当前创作者账号无权进入系统管理员工作台。": "admin.adminAccessDenied",
  "请选择有效的达人账号。": "admin.selectValidCreator",
  "系统管理员": "admin.systemAdministrator",
  "待处理": "admin.pending",
  "已暂停": "admin.paused",
  "系统": "admin.systemOwner",
  "你": "admin.youOwner",
  "合同匹配": "admin.contractMatched",
  "已匹配当前账号下的同名合同": "admin.contractMatchDescription",
  "Invoice 签署": "admin.invoiceSigning",
  "Invoice 已完成签署": "admin.invoiceSigned",
  "等待你核对并签署 Invoice": "admin.awaitingInvoiceSignature",
  "Invoice 审核": "admin.invoiceReview",
  "Invoice 已通过审核": "admin.invoiceApproved",
  "付款资料修正后已从资料审核节点重新开始": "admin.reviewRestarted",
  "Invoice 正在审核": "admin.invoiceUnderReview",
  "签署后进入审核": "admin.reviewAfterSigning",
  "完成付款": "admin.completePayment",
  "款项已完成支付": "admin.paymentCompleted",
  "付款信息校验失败，需要修正后提交审核": "admin.paymentCorrectionRequired",
  "等待付款处理": "admin.awaitingPaymentProcessing",
  "Invoice 审核通过后进入付款": "admin.paymentAfterApproval",
  "请核对识别结果与收款账户": "admin.verifyRecognitionAccount",
  "请核对内容并完成确认": "admin.reviewAndConfirm",
  "资料已提交，等待审核": "admin.submittedForReview",
  "审核未通过，请按原因修改": "admin.reviewReturned",
  "付款处理中断，请修正收款信息": "admin.paymentInterrupted",
  "审核完成，等待付款": "admin.reviewDoneAwaitingPayment",
  "等待确认 Invoice 识别结果": "admin.awaitingRecognitionConfirmation",
  "等待你确认关联 Invoice": "admin.awaitingLinkedInvoiceConfirmation",
  "Invoice 已提交，正在审核": "admin.invoiceSubmittedReview",
  "审核退回，等待修改 Invoice": "admin.invoiceReturned",
  "付款处理中断，需要修正收款信息": "admin.paymentInterruptedCorrection",
  "Invoice 已通过审核，等待付款": "admin.invoiceApprovedAwaitingPayment",
  "关联 Invoice 已完成付款": "admin.linkedInvoicePaid",
  "登录会话已失效，请重新登录": "service.sessionExpired",
  "达人不存在或无权查看": "service.creatorUnavailable",
  "无权查看其他达人的资料": "service.otherCreatorForbidden",
  "管理员只读模式不能执行达人操作": "service.adminReadOnly",
  "当前账号无权操作该 Invoice": "service.invoiceForbidden",
  "Invoice 不存在": "invoice.notFound",
  "当前 Invoice 不是外部 Invoice": "service.notExternalInvoice",
  "仅支持 PDF、PNG 或 JPEG 文件": "service.unsupportedFile",
  "文件大小必须在 5MB 以内": "service.fileTooLarge",
  "请选择已验证且可用于收款的账户": "service.selectVerifiedAccount",
  "当前 Invoice 不能确认": "service.cannotConfirmInvoice",
  "Invoice 尚未生成 AI 识别结果": "service.recognitionPending",
  "所选收款账户已失效，请重新选择": "service.accountUnavailable",
  "Invoice 金额与系统下发金额不一致": "service.amountMismatch",
  "Invoice 币种与系统下发币种不一致": "service.currencyMismatch",
  "Invoice From 与个人档案 Real Name 不一致": "service.fromMismatch",
  "Bill To 必须为 COMETS INTERNATIONAL LIMITED": "service.billToMismatch",
  "当前状态不允许上传 Invoice 文件": "service.uploadStateInvalid",
  "当前状态不能执行识别": "service.recognitionStateInvalid",
  "请先上传 Invoice 文件": "service.uploadFirst",
  "当前状态不允许修改识别结果": "service.correctionStateInvalid",
  "缺少识别结果或文件版本": "service.recognitionMissing",
  "收款信息格式不正确，请重新核对": "service.payoutFormatInvalid",
  "当前状态不允许更换收款账户": "service.accountSwitchInvalid",
  "请选择已验证且可用的收款账户": "service.selectUsableAccount",
  "请选择与当前不同的收款账户": "service.chooseDifferentAccount",
  "核对页不存在": "service.pageUnavailable",
  "当前状态不能确认本页": "service.pageConfirmationInvalid",
  "当前文件没有有效模拟识别值": "service.recognitionValuesUnavailable",
  "本页已确认；修改字段后才能重新确认": "service.pageAlreadyConfirmed",
  "当前 Invoice 不能提交审核": "service.reviewSubmissionInvalid",
  "请先分别确认 Invoice 信息与收款信息": "service.confirmBothPages",
  "管理员只读视图不能替达人签署合同": "service.adminCannotSign",
  "当前账号无权签署该合同": "service.contractForbidden",
  "合同不存在": "service.contractNotFound",
  "只有待签署合同可以签署": "service.contractNotPending",
  "请完成签名并确认签署声明": "service.signatureRequired",
  "只有待签署的 Comets内部invoice可以签署": "service.internalSignInvalid",
  "该 Invoice 已完成签署，不能重复操作": "service.invoiceAlreadySigned",
  "请先在个人档案设置可用的主收款账户，再签署 Invoice": "service.primaryAccountRequired",
  "只有待签署的 Comets内部invoice可以提交信息反馈": "service.feedbackStateInvalid",
  "问题类型和问题说明不能为空": "service.feedbackRequired",
  "Comets内部invoice的收款信息由支付管理端同步，不支持修改": "service.internalPayoutReadOnly",
  "当前 Invoice 状态不允许更换收款账户": "service.invoiceAccountSwitchInvalid",
  "当前 Invoice 不能申请重新打款": "service.retryInvalid",
  "请选择当前达人已验证且可用的收款账户": "service.selectOwnUsableAccount",
  "收款账户或资料已变化，请重新核对后提交": "service.accountChanged",
  "当前 Invoice 不在付款失败修正流程中": "service.notInRecovery",
  "收款资料已提交，不能重复操作": "service.correctionAlreadySubmitted",
  "请修改错误字段或选择其他已验证收款账户后再提交": "service.correctionMustChange",
  "新收款账户必须已通过验证且处于可用状态": "service.newAccountInvalid",
  "收款资料已提交复核": "service.correctionSubmitted",
  "个人档案已保存": "service.profileSaved",
  "银行账号仅支持数字": "schema.accountDigitsOnly",
  "银行账号应为 4 至 17 位数字": "schema.usAccountLength",
  "英国本地银行账号应为 8 位数字": "schema.ukAccountLength",
  "日本本地银行账号应为 7 位数字": "schema.jpAccountLength",
  "银行账号仅支持字母和数字": "schema.accountAlphanumeric",
  "银行账号应为 6 至 34 位字符": "schema.accountLength",
  "收款账户名首尾不能包含空格": "schema.accountNameNoEdgeSpaces",
  "银行名称包含不支持的字符": "schema.bankNameCharacters",
  "银行名称应为 2 至 140 位字符": "schema.bankNameLength",
  "银行地址应为 5 至 200 位字符": "schema.bankAddressLength",
  "银行地址首尾不能包含空格": "schema.bankAddressNoEdgeSpaces",
  "IBAN 校验位不正确，请核对完整账号": "schema.ibanChecksum",
  "收款账户名仅支持英文字母和空格": "schema.accountNameEnglish",
  "请填写账户别名": "profile.aliasRequired",
  "账户别名至少需要 2 个字符": "profile.aliasTooShort",
  "待确认": "status.awaitingConfirmation",
  "待审核": "status.awaitingReview",
  "审核中": "status.underReview",
  "待修改": "status.changesRequired",
  "付款异常": "status.paymentIssue",
  "待付款": "status.awaitingPayment",
  "已付款": "status.paid",
  "待签署": "status.awaitingSignature",
  "执行中": "status.active",
  "已过期": "status.expired",
  "已完成": "status.completed",
  "等待付款": "status.waitingPayment",
  "付款处理中": "status.processingPayment",
  "付款失败": "status.failedPayment",
  "付款成功": "status.successfulPayment",
  "未开始": "status.notStarted",
  "待上传": "status.waitingUpload",
  "识别中": "status.recognizing",
  "待重新上传": "status.waitingReupload",
  "待补充": "status.missing",
  "已认证": "status.verified",
  "待认证": "status.pendingVerification",
  "待修正": "status.needsCorrection",
  "校验通过": "status.validated",
  "暂未开放": "status.unavailable",
  "当前无需操作": "status.noActionNeeded",
  "反馈处理中": "status.feedbackProcessing",
  "已通过审核": "status.approved",
  "待发布": "status.unpublished",
  "识别失败": "status.recognitionFailed",
  "已取消": "status.cancelled",
  "审核通过": "status.reviewApproved",
  "待确认重试方案": "status.retryDecisionPending",
  "重新打款申请已提交复核": "status.retrySubmittedForReview",
  "等待重新付款": "status.waitingRetry",
  "签署 Invoice": "status.signInvoice",
  "信息反馈处理中": "status.feedbackInProgress",
  "审核未通过": "status.reviewFailed",
  "资料审核": "status.documentReview",
  "等待修改 Invoice": "status.waitingInvoiceCorrection",
  "上传文件未通过": "status.uploadRejected",
  "上传 Invoice": "status.uploadInvoice",
  "等待重新上传": "status.waitingReupload",
  "识别与确认": "status.recognitionConfirmation",
  "等待重新识别": "status.waitingRecognition",
  "收款信息有误": "invoice.payoutIssue",
  "金额或币种有误": "invoice.amountCurrencyIssue",
  "Invoice 主体有误": "invoice.partyIssue",
  "其他信息有误": "invoice.otherIssue",
  "审核通过后 3-5 个工作日": "invoice.afterApprovalDays",
  "请填写完整的主页链接": "auth.completeProfileLinks",
  "请输入以 http:// 或 https:// 开头的有效主页链接": "auth.invalidProfileLink",
  "请至少上传一张社媒账号后台截图": "auth.screenshotRequired",
  "请上传 8MB 以内的 PNG 或 JPG 截图": "auth.invalidScreenshot",
  "后台截图最多上传 6 张": "auth.tooManyScreenshots",
  "请先完成账号归属验证": "auth.verifyOwnershipFirst",
  "请完成所有基本信息": "auth.completeBasicInformation",
  "请阅读并同意服务协议与隐私政策": "auth.agreeTermsPrivacyError",
  "请选择已开放的收款渠道并等待表单加载": "auth.chooseOpenChannel",
  "转账方式加载失败，请重试。": "auth.transferMethodsFailed",
  "付款信息校验失败": "auth.beneficiaryFailed",
  "请选择 Invoice 文件": "invoice.fileRequired",
  "仅支持 PDF、PNG 或 JPG 文件": "invoice.unsupportedFile",
  "文件大小不能超过 5MB": "invoice.fileTooLarge",
  "上传失败，请稍后重试": "invoice.uploadFailed",
  "经典": "invoice.styleClassic", "流畅": "invoice.styleFlowing",
  "简约": "invoice.styleMinimal", "个性": "invoice.stylePersonal",
  "请先在签名板完成签名": "invoice.drawFirst",
  "请先选择一种电子签名样式": "invoice.chooseStyleFirst",
  "请阅读并同意签署声明": "invoice.acceptSigningConsent",
  "签署失败，请稍后重试": "invoice.signFailed",
  "仅英文字母，姓名间用单个空格": "schema.accountNameHint",
  "格式要求：仅支持英文字母，姓名各部分用单个空格分隔，不支持数字或符号": "schema.accountNameRule",
  "4 至 17 位数字，不含空格或符号": "schema.usAccountHint",
  "8 位数字，不含空格或符号": "schema.ukAccountHint",
  "7 位数字，不含空格或符号": "schema.jpAccountHint",
  "6 至 34 位字母或数字，不含空格或符号": "schema.accountHint",
  "格式要求：4 至 17 位数字，不含空格、连字符或其他符号": "schema.usAccountRule",
  "格式要求：8 位数字，不含空格、连字符或其他符号": "schema.ukAccountRule",
  "格式要求：7 位数字，不含空格、连字符或其他符号": "schema.jpAccountRule",
  "格式要求：6 至 34 位英文字母或数字，不含空格、连字符或其他符号": "schema.accountRule",
  "2 至 140 位，可含字母、数字及常用符号": "schema.bankNameHint",
  "格式要求：2 至 140 位，可使用字母、数字、空格及 . , & ' ( ) / -": "schema.bankNameRule",
  "5 至 200 位英文地址，含街道/城市/州省/邮编": "schema.bankAddressHint",
  "格式要求：使用 5 至 200 位英文字符，按街道、城市、州/省、邮编顺序填写完整地址": "schema.bankAddressRule",
  "8 或 11 位英文字母/数字，不含空格": "schema.swiftHint",
  "格式要求：8 或 11 位英文字母/数字，不含空格；前 4 位为银行代码、接 2 位国家代码和 2 位地区代码，可再加 3 位分行代码": "schema.swiftRule",
  "9 位数字，不含空格或符号": "schema.routingHint",
  "4 位数字，不含空格或符号": "schema.bankCodeHint",
  "3 位数字，不含空格或符号": "schema.branchCodeHint",
  "格式要求：4 位数字，不含空格或符号": "schema.bankCodeRule",
  "格式要求：3 位数字，不含空格或符号": "schema.branchCodeRule",
  "管理员仅可查看外部 Invoice；票面信息须由达人在待确认或退回修改阶段处理。": "invoice.adminExternalReadOnly",
  "已提交审核，暂不能修改 Invoice 信息；如需调整请等待审核退回。": "invoice.submittedReadOnly",
  "此 Invoice 已审核通过，票面信息不可修改。付款失败请在“收款信息”页处理账户。": "invoice.approvedReadOnly",
  "重新打款申请已提交财务复核": "invoice.retryRequestSubmitted",
  "Invoice 已签署并进入审核": "invoice.invoiceSigned",
  "Invoice 反馈已提交": "invoice.feedbackSubmitted",
  "收款资料未通过付款校验": "invoice.paymentValidationFailed",
  "Invoice 信息已确认，请继续核对收款信息": "invoice.invoiceInformationConfirmed",
  "纠正值已保存，初始模拟值已保留": "invoice.correctedValuesSaved",
  "收款信息已确认": "invoice.payoutConfirmed",
  "收款账户已选择，请核对并确认本页": "invoice.accountSelected",
  "Invoice 已确认并提交审核": "invoice.invoiceSubmitted",
  "重新识别完成，请核对结果": "invoice.recognitionRetried",
  "识别结果已在当前页面展示；核对 Invoice 信息后，请选择收款账户并确认": "invoice.uploadResultShown",
  "操作失败，请稍后重试": "invoice.operationFailed",
  "当前场景暂无可用转账方式，请调整付款场景。": "profile.methodsUnavailable",
  "付款信息加载失败，请重新选择付款场景。": "profile.schemaLoadFailed",
  "请完成必填字段：联系邮箱 / Email": "profile.emailRequired",
  "请输入有效的联系邮箱地址": "profile.emailInvalid",
  "请等待付款信息加载完成后再保存": "profile.waitForPayoutForm",
  "请检查 Airwallex 付款信息中的标记字段": "profile.checkMarkedFields",
  "账户操作失败，请稍后重试。": "profile.accountActionFailed",
  "每个收款渠道最多保留一个账户。": "profile.oneAccountPerChannel",
  "仅已验证且未停用的账户可设为默认账户。": "profile.defaultRequiresVerified",
  "该账户正在处理中，完成后才能停用。": "profile.processingAccountLocked",
  "收款账户已删除": "profile.accountDeleted", "收款账户已停用": "profile.accountDisabled",
  "收款账户已重新启用": "profile.accountReenabled",
  "未命名 Airwallex 账户": "profile.unnamedAirwallex",
  "搜索操作者、用户、摘要或原因": "admin.searchAudit",
  "筛选操作类型": "admin.filterAction", "筛选操作者": "admin.filterActor",
  "筛选用户对象": "admin.filterSubject", "筛选操作模块": "admin.filterModule",
  "开始日期": "admin.startDate", "结束日期": "admin.endDate",
  "条日志": "admin.auditUnit",
  "设置已保存": "admin.settingsSaved", "设置保存失败": "admin.settingsSaveFailed",
  "修改要求已发送": "admin.correctionSent", "发送失败": "admin.sendFailed",
  "社媒认证截图": "admin.socialScreenshots", "收款账户名称": "admin.payoutAccountName",
  "主页链接": "admin.profileLinks", "真实姓名": "admin.realName",
  "联系邮箱": "admin.contactEmail", "联系电话": "admin.phone", "联系地址": "admin.contactAddress",
  "查看已记录": "admin.revealRecorded", "无法查看": "admin.revealFailed",
  "条登录记录": "admin.loginUnit", "条通知": "admin.notificationUnit",
  "条操作记录": "admin.activityUnit",
  "搜索项目、达人、Creator ID、合同或 Invoice": "admin.searchProjects",
  "搜索合同、项目、品牌、达人或 Creator ID": "admin.searchContracts",
  "搜索 Invoice、项目、达人或 Creator ID": "admin.searchInvoices",
  "筛选创作者": "admin.filterCreator", "个项目": "admin.projectUnit",
  "份合同": "admin.contractUnit", "份 Invoice": "admin.invoiceUnit",
  "正在同步": "profile.syncing", "同步失败": "profile.syncFailed", "已同步": "profile.synced",
  "此项未通过付款校验，请填写正确的信息。": "profile.paymentFieldRejected",
  "Comets内部invoice": "invoice.internalType",
  "外部 Invoice": "invoice.externalType",
  "全部": "common.all",
  "请选择": "common.select",
  "个人 / Individual": "profile.individual",
  "企业 / Company": "profile.company",
  "法国 / France": "country.france",
  "日本 / Japan": "country.japan",
  "美国 / United States": "country.unitedStates",
  "英国 / United Kingdom": "country.unitedKingdom",
  "澳大利亚 / Australia": "country.australia",
  "新加坡 / Singapore": "country.singapore",
  "中国香港 / Hong Kong SAR": "country.hongKong",
  "通知中心": "layout.notificationCenter",
  "合同": "menu.contracts",
  "个账号": "admin.accountUnit",
  "用户管理": "menu.users",
  "操作日志": "menu.auditLogs",
  "管理管理员与创作者账号、认证状态和访问权限。": "admin.usersDescription",
  "搜索姓名、邮箱或 Creator ID": "admin.searchUsers",
  "筛选账号角色": "admin.filterRole", "筛选账号状态": "admin.filterAccountStatus",
  "筛选认证状态": "admin.filterVerification", "筛选邀请状态": "admin.filterInvitation",
  "筛选资料修正状态": "admin.filterCorrections",
  "启用所选账号": "admin.enableSelected", "停用所选账号": "admin.disableSelected",
  "账号状态已更新": "admin.accountStatusUpdated", "操作失败": "admin.actionFailed",
  "脱敏用户清单已导出": "admin.maskedExported",
  "请填写用户姓名和有效邮箱": "admin.nameEmailRequired",
  "用户已创建": "admin.userCreated", "创建失败": "admin.createFailed",
  "密码重置邮件已发送": "admin.passwordResetSent",
  "认证状态已更新": "admin.verificationUpdated",
  "用户档案已更新": "admin.profileUpdated", "用户档案保存失败": "admin.profileSaveFailed",
  "银行账号": "admin.bankAccount", "个人证件号": "admin.identityNumber",
  "公司注册号": "admin.registrationNumber", "待完善": "admin.needsInformation",
  "多平台": "profile.multiplePlatforms",
  "使用说明": "menu.help",
  "个人档案": "menu.profile",
  "收款账户": "profile.payoutAccount",
  "合同金额": "contracts.amount",
  "手续费承担方": "contracts.feeBearer",
  "付款渠道": "contracts.paymentChannel",
  "付款方式/付款渠道": "contracts.paymentMethodChannel",
  "账号已认证": "profile.accountVerified",
  "资料待修正": "profile.profileNeedsCorrection",
  "认证中": "profile.verificationInProgress",
  "管理员": "admin.roleAdministrator", "创作者": "admin.roleCreator",
  "已启用": "admin.enabled", "已停用": "admin.disabled",
  "自主注册": "admin.selfRegistered", "待接受": "admin.invitationPending",
  "已接受": "admin.invitationAccepted", "登录": "auth.signIn",
  "创建账号": "admin.auditCreateAccount", "邀请用户": "admin.auditInviteUser",
  "账号状态变更": "admin.auditAccountStatus", "密码重置": "admin.auditPasswordReset",
  "档案更新": "admin.auditProfileUpdated", "认证状态更新": "admin.auditVerificationUpdated",
  "资料退回": "admin.auditCorrectionCreated", "修正自动关闭": "admin.auditCorrectionResolved",
  "查看敏感信息": "admin.auditSensitiveReveal", "导出用户": "admin.auditExportUsers",
  "更新设置": "admin.auditSettingsUpdated", "外部数据同步": "admin.auditExternalSync",
  "外部数据拒绝": "admin.auditExternalRejected", "达人操作": "admin.auditCreatorAction",
};

export function displayCopy(value: string, t: TFunction): string {
  const aliasLength = value.match(/^账户别名不能超过 (\d+) 个字符$/);
  if (aliasLength) return t("profile.aliasTooLong", { max: Number(aliasLength[1]) });
  const ibanCompact = value.match(/^([A-Z]{2})开头｜共(\d+)位｜仅大写字母\/数字｜无空格\/连字符$/);
  if (ibanCompact) return i18n.resolvedLanguage === "en" ? t("schema.ibanCompact", { country: ibanCompact[1], length: ibanCompact[2] }) : value;
  const ibanCompactRange = value.match(/^([A-Z]{2})开头｜共15至34位｜仅大写字母\/数字｜无空格\/连字符$/);
  if (ibanCompactRange) return i18n.resolvedLanguage === "en" ? t("schema.ibanCompactRange", { country: ibanCompactRange[1] }) : value;
  const ibanRule = value.match(/^(IBAN )?格式要求：([A-Z]{2}) \+ 2 位校验码 \+ (\d+) 位大写字母或数字，共 (\d+) 位[；，]不含空格或连字符$/);
  if (ibanRule) return i18n.resolvedLanguage === "en" ? t("schema.ibanRule", { country: ibanRule[2], body: ibanRule[3], length: ibanRule[4] }) : value;
  const ibanRuleRange = value.match(/^(IBAN )?格式要求：([A-Z]{2}) \+ 2 位校验码 \+ 11 至 30 位大写字母或数字[；，]不含空格或连字符$/);
  if (ibanRuleRange) return i18n.resolvedLanguage === "en" ? t("schema.ibanRuleRange", { country: ibanRuleRange[2] }) : value;
  const multipleProfiles = value.match(/^(.+) 等 (\d+) 个主页$/);
  if (multipleProfiles) return t("home.socialProfiles", { name: multipleProfiles[1], count: Number(multipleProfiles[2]) });
  const defaultAccount = value.match(/^已将“(.+)”设为默认收款账户$/);
  if (defaultAccount) return t("profile.defaultChanged", { name: defaultAccount[1] });
  const unavailableProvider = value.match(/^(.+) 账户暂未开放，当前仅支持查看账户状态。$/);
  if (unavailableProvider) return t("profile.providerUnavailableToast", { provider: unavailableProvider[1] });
  const period = value.match(/^(\d{4}-\d{2}-\d{2})\s+至\s+(\d{4}-\d{2}-\d{2})$/);
  if (period) return t("contracts.periodRange", { start: period[1], end: period[2] });
  const today = value.match(/^今天\s+(.+)$/);
  if (today) return t("home.todayAt", { time: today[1] });
  const yesterday = value.match(/^昨天\s+(.+)$/);
  if (yesterday) return t("home.yesterdayAt", { time: yesterday[1] });
  if (value === "刚刚") return t("home.justNow");
  const key = keys[value];
  if (key) return t(key);
  const bilingual = value.match(/^.*?[\u3400-\u9fff].*?\s\/\s([A-Z][A-Za-z ].*)$/);
  return bilingual && i18n.resolvedLanguage === "en" ? bilingual[1] : value;
}
